string DLG_TEXT[229] = {
    "Hola. Déjame darte un humilde consejo",
    "Estaré encantado de escucharlo.",
    "No necesito tu consejo",
    "Saludos. ¿Tiene prisa?",
    "Sí, por negocios",
    "No le concierne",
    "Buenas tardes. ¿Qué tal?",
    "Nada.",
    "No tengo tiempo para hablar con usted aquí",
    "Hola. No te había visto antes por aquí",
    "Sí, estoy de paso",
    "No tengo tiempo para hablar con usted aquí",
    "Saludos. Me alegro de verle en nuestra zona",
    "Hola.",
    "Lo siento, no puedo hablar con usted en este momento",
    "Hola. ¿Quieres oír un buen consejo?",
    "Hola. Vamos, dímelo",
    "No tengo ganas de perder el tiempo",
    "Hola. Tengo algunos artículos que podrían interesarte",
    "Vamos a regatear",
    "No tengo tiempo para hablar con usted aquí",
    "Buenas tardes. Pareces cansado. Por sólo 200 monedas, puedo curar tus heridas y aliviar tu fatiga",
    "Dame tu bebida",
    "No creo en curas milagrosas",
    "Hola. Estoy en un apuro, ¿puedes ayudarme?",
    "Hmm, ¿por qué estoy...",
    "Estos son tus problemas, resuélvelos tú mismo",
    "¿No ayudarás al pobre que sufre, no aliviarás su suerte con un par de monedas?",
    "Por supuesto, la iglesia nos enseña a escuchar, y ayudar a los demás",
    "Pasa, pobre hombre, y no te atrevas a acercarte a mí otra vez.",
    "No dejes a un mendigo en apuros, ¿me darías una moneda para que no me muera de hambre?",
    "De qué hablas, quédate con 200 monedas",
    "Pasa, pobre hombre, y no te atrevas a acercarte a mí otra vez.",
    "Hola. Veo que vas armado, seguro que participas a menudo en peleas",
    "Sí, claro",
    "Este es mi negocio. Adiós",
    "Hola. No es frecuente ver a un individuo tan importante en nuestro desierto. ¿Usted debe ser el capitán?",
    "Sí, ¿en qué puedo ayudarle?",
    "Sabe, tengo prisa. Adiós",
    "Buenas tardes. ¿Usted se pasea por aquí así, sin hacer nada?",
    "En realidad, sí, puedo hablar con usted",
    "No, estoy ocupado",
    "Escucha, no aparezcas en la selva por la noche. Los bandidos suelen ir allí y atacan sin avisar",
    "Gracias por el consejo.",
    "Si tienes problemas con la ley, será mejor que no te cruces con una patrulla. Aquí hay muchos soldados. Será mejor que salgas de la isla",
    "Interesante",
    "No estoy interesado en este tipo de consejos. Adiós",
    "Pero prepárate para una fría bienvenida la próxima vez que navegues por aquí",
    "Bien, lo tendré en cuenta, adiós",
    "Conozco una forma segura de restablecer la salud si algo anda mal contigo. Puedes comprar una botella a un vendedor de la ciudad",
    "Sí, ¿y además de eso?",
    "No tengo tiempo para hablar",
    "Además, si descansas en la taberna, aumentará tu vitalidad",
    "Gracias",
    "Sabes, si necesito las últimas noticias o cualquier información, siempre acudo al tabernero. Él puede responder a casi todas tus preguntas",
    "Gran consejo, lo usaré",
    "Veo que eres militar. Y tienes que participar en combates. Recuerda llevar más oficiales contigo. A veces es imposible sobrevivir sin refuerzos",
    "Sí, claro",
    "Veo por tu postura que eres el capitán, nada menos. Si necesitas un barco, cómpralo en nuestro astillero. Si de repente no hay exactamente la nave que querías comprar, vuelve dentro de unos días, quizá para entonces ya esté a la venta",
    "Buen consejo, gracias",
    "A veces aparecen en estos lugares personas que han visto mucho en este mundo. Puedes pedirles ayuda, y ellos podrán mejorar tus habilidades en una o varias áreas. Estoy seguro de que sus conocimientos son casi impagables",
    "Buen consejo, gracias",
    "Si me das 200 monedas, le diré a todo el mundo lo maravillosa persona que eres. No importa que sea pobre, tengo muchos amigos, siempre serás bienvenido aquí",
    "¿Tirar dinero sólo para que un tonto cuente historias sobre mí? Pues no",
    "¿Sí? Bueno, 200 monedas no es tal cantidad como para no donársela a alguien que tanto lo necesita",
    "Gracias por lo que has hecho. Te lo agradeceré como pueda. Bebe esta tintura, te devolverá la vitalidad",
    "Gracias a ti también.",
    "Gracias, pero no tengo nada para darte y expresarte mi gratitud, toma esta cosita, tal vez puedas beneficiarte de ella.",
    "Con mucho gusto aceptaré tu regalo",
    "Gracias, es usted muy amable",
    "No, gracias, adiós",
    "Capitán, lléveme a su barco, hace tiempo que sueño con largos viajes por mar y feroces batallas",
    "Por supuesto que serás mi oficial",
    "No, no necesito novatos",
    "Págame y te enseñaré un par de trucos para vencer a cualquiera en combate cuerpo a cuerpo. ¿O quieres aprender algunos movimientos defensivos?",
    "No necesito tus consejos, ya lo sé todo",
    "Enséñame las técnicas de defensa",
    "No necesito tus consejos, ya lo sé todo",
    "Muéstrame cómo atacar",
    "Gracias, no necesito nada",
    "Yo también fui marinero una vez, un famoso navegante. Puedo decirte mucho sobre cómo dirigir a la tripulación de un barco",
    "No necesito tus consejos, ya lo sé todo",
    "Sí, quiero saber más",
    "Gracias, no necesito nada",
    "También soy marinero, navegante. Por un módico precio, te contaré mis secretos, que te permitirán manejar mejor el barco",
    "No necesito sus consejos, ya lo sé todo.",
    "Sí, quiero aprender sus secretos de maniobra",
    "Gracias, no necesito nada",
    "Fui artillero en un buque de guerra británico. Estaré encantado de decirle cómo calcular correctamente la trayectoria de la bala de cañón y dar siempre en el blanco",
    "No necesito tus consejos, ya lo sé todo",
    "Dígame, le pagaré lo que me pida",
    "Gracias, no necesito nada",
    "Fui artillero en un buque de guerra británico. Puedo decirte cómo recargar rápidamente tus armas",
    "No necesito su consejo, ya lo sé todo.",
    "Dígame, le pagaré lo que me pida",
    "Gracias, no necesito nada",
    "Fui oficial en un buque de guerra británico. Puedo contarte muchas historias sobre el arte del abordaje",
    "No necesito sus consejos, ya lo sé todo",
    "Dígame, le pagaré lo que me pida",
    "Gracias, no necesito nada",
    "Trabajo en un astillero y soy muy bueno construyendo y reparando barcos. Si me pagas, entrenaré a tu tripulación para reparar rápidamente un barco",
    "No necesito tus consejos, ya lo sé todo",
    "Dígame, le pagaré lo que me pida",
    "Gracias, no necesito nada",
    "Soy comerciante, puedo enseñarte técnicas comerciales que te permitirán aumentar los beneficios de tus negocios",
    "No necesito tus consejos, ya lo sé todo",
    "Dígame, le pagaré lo que me pida",
    "Gracias, no necesito nada",
    "Bueno, ¿me pagará,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dígame",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "¿por técnicas secretas de combate cuerpo a cuerpo?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime.",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime.",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "por técnicas secretas de defensa?",
    "Parece que no tengo suficiente dinero.",
    "Sí, lo intentaré, dime.",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime.",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "por las lecciones de guiar a la gente?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime.",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "por un consejo para gobernar el barco?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero.",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "por un consejo para disparar cañones?",
    "Parece que no tengo suficiente dinero.",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "por consejos sobre recarga de armas?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, ¿me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, ¿me pagarías,",
    "por un consejo sobre el aborto?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, ¿cuánto me vas a pagar,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "por el consejo de reparar el barco?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado",
    "Bueno, me pagarás,",
    "¿para ayuda en el comercio?",
    "Parece que no tengo suficiente dinero",
    "Sí, lo intentaré, dime",
    "No, es demasiado.",
    "Gracias por su ayuda, es muy amable",
    "No es necesario, me alegro de haber podido ayudar.",
    "Bueno, ¿quieres comprar más elixires?",
    "Sí, tal vez más.",
    "No, lo siento.",
    "Bueno, ¿quieres regatear?",
    "Sí, quiero comprarte algo",
    "No, lo siento.",
    "¿Qué es lo que quieres? Creo que ya lo hemos hablado todo",
    "No importa.",
    "¿Qué órdenes, capitán?",
    "Ninguna",
    "¿Quiere algún consejo?",
    "Sí, me interesa lo que tiene que decir",
    "No, lo siento",
    "Escucha, lleva una vida recta y mucha gente será feliz contigo",
    "Gracias por el consejo",
    "No te aconsejo que vengas aquí si tienes problemas con la ley. Aquí hay muchos soldados. Será mejor que navegues lejos de la isla",
    "Interesante",
    "No estoy interesado en este tipo de consejos. Adiós",
    "Conozco una forma certiana de restaurar la salud si algo anda mal contigo. Puedes comprar una botella a un vendedor de la ciudad",
    "Sí, ¿y además de eso?",
    "No tengo tiempo para hablar",
    "Sabes, si necesito las últimas noticias o cualquier información, siempre acudo al posadero. Él puede responder a casi todas tus preguntas",
    "Gran consejo, lo usaré",
    "Veo que eres militar. Y a menudo tienes que participar en combates. Recuerda, lleva más oficiales contigo. A veces es imposible sobrevivir sin refuerzos",
    "Sí, claro",
    "Veo por tu postura que eres el capitán, nada menos. Si necesitas un barco, cómpralo en nuestro astillero. Si de repente no hay exactamente la nave que querías comprar, vuelve dentro de unos días, quizá para entonces ya esté a la venta",
    "Buenos consejos, gracias",
    "A veces aparecen en estos lugares personas que han visto mucho en este mundo. Puedes pedirles ayuda, y ellos podrán aumentar tu nivel de conocimientos en una o varias áreas. Estoy seguro de que sus conocimientos son casi impagables",
    "Buenos consejos, gracias",
};