string DLG_TEXT[229] = {      
"Hello. Let me give you some humble advice.",
"I'll be glad to hear it.",
"I don't need your advice.",
"Greetings. Are you in a hurry?",
"Yes, on business.",
"Doesn't concern you.",
"Good afternoon. How are you?",
"Nothing.",
"I don't have time to talk to you here.",
"Hello. I haven't seen you here before.",
"Yes, I'm passing through.",
"I don't have time to talk to you here.",
"Greetings. Glad to see you in our area.",
"Hello.",
"Sorry, I can't talk to you right now.",
"Hello. Do you want to hear some good advice?",
"Hi there. Come on, lay it out.",
"I have no desire to waste time.",
"Hi. I have some items you might be interested in.",
"Let's haggle.",
"I don't have time to talk to you here.",
"Good afternoon. You look tired. For only 200 coins, I can heal your wounds and relieve your fatigue.",
"Give me your drink.",
"I don't believe in miracle cures.",
"Hello. I'm in a predicament, can you help me?",
"Hmm, why am I...",
"These are your problems, solve them yourself.",
"Won't you help the poor sufferer, won't you ease his lot with a couple of coins?",
"Of course, the church teaches us to listen, and help the others.",
"Pass on, poor man, and don't you dare approach me again.",
"Don't leave a beggar in trouble, would you give me a coin so I don't starve to death.",
"What are you talking about, keep 200 coins.",
"Pass on, poor man, and don't you dare approach me again.",
"Hello. I see you are armed, surely you often participate in fights?",
"Yes, sure.",
"This is my business. Farewell.",
"Hello. It's not often you see such important individual in our wilderness. You must be the captain?",
"Yes, how can I help you?",
"You know, I'm in a hurry. Farewell.",
"Good afternoon. Do you walk around here just like that, doing nothing?",
"Actually, yes, I can talk to you.",
"No, I'm busy.",
"Listen, don't show up in the jungle at night. Bandits often go there and attack without warning.",
"Thanks for the advice.",
"If you're in trouble with the law, then you'd better not run into a patrol. There are a lot of soldiers here. You'd better get off the island.",
"Interesting.",
"I'm not interested in this kind of advice. Goodbye.",
"But be prepared for a cold welcome the next time you sail here.",
"Fine, I'll take it into account, goodbye.",
"I know a sure way to restore health if something is wrong with you. You can buy a bottle from a vendor in the city.",
"Yes, and besides that?",
"I don't have time to talk.",
"Well, also, if you rest in the tavern, it will increase your vitality.",
"Thank you.",
"You know, if I need the latest news or any information, I always go to the tavern keeper. He can answer almost all your questions.",
"Great advice, I'll use it.",
"I see you are a military man. And you have to participate in fights. Remember to take more officers with you. Sometimes it is impossible to survive without backup.",
"Yes, sure.",
"I can see from your stance that you are the captain, nothing less. If you need a ship, buy it at our shipyard. If suddenly there is not exactly the ship that you wanted to buy, come back in a few days, maybe by this time it will be up for sale.",
"Good advice, thanks.",
"Sometimes people who have seen a lot in this world appear in these places. You can ask them for help, and they will be able to improve your skills in one or more areas. I know for sure, their knowledge is almost priceless.",
"Good advice, thanks.",
"If you give me 200 coins, I will tell everyone what a wonderful person you are. It doesn't matter that I am poor, I have many friends, you will always be welcome here.",
"Tossing money around just to have some fool tell stories about me? Well, no.",
"Yes? Well, 200 coins is not such an amount that you don't donate it to someone who needs it so much.",
"Thank you for what you have done. For this I will thank you in any way I can. Drink this tincture, it will restore your vitality.",
"Thank you too.",
"Thank you, but I don't have anything to give you and express my gratitude, take this little thing, maybe you can benefit from it.",
"I will gladly accept your gift.",
"Thank you, you're too kind.",
"No thanks, goodbye.",
"Captain, take me to your ship, I have long dreamed of long sea voyages and fierce battles.",
"Of course you will be my officer.",
"No, I don't need rookies.",
"Pay me and I'll show you a couple of tricks to beat anyone in hand-to-hand combat. Or do you want to learn a few defensive moves?",
"I don't need your advice, I already know everything.",
"Show me the defense techniques.",
"I don't need your advice, I already know everything.",
"Show me how to attack.",
"Thank you, I don't need anything.",
"I was also a sailor once, a famous navigator. I can tell you a lot about how to manage the crew on a ship.",
"I don't need your advice, I already know everything.",
"Yes, I want to know more about it.",
"Thank you, I don't need anything.",
"I am also a sailor, navigator. For a small fee, I will tell you my secrets, which will allow you to better manage the ship.",
"I don't need your advice, I already know everything.",
"Yes, I want to learn your maneuvering secrets.",
"Thank you, I don't need anything.",
"I was a gunner on a British warship. I'll be happy to tell you how to correctly calculate the trajectory of the cannonball and hit the target every time.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thank you, I don't need anything.",
"I was a gunner on a British warship. I can tell you how to quickly reload your guns.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thank you, I don't need anything.",
"I was an officer on a British warship. I can tell you many stories about the art of boarding.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thank you, I don't need anything.",
"I work in a shipyard and I'm very good at building and repairing ships. If you pay me, I'll train your crew to quickly repair a ship.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thank you, I don't need anything.",
"I am a merchant, I can teach you trading techniques that will allow you to increase the profits from your business ventures.",
"I don't need your advice, I already know everything.",
"Tell me, I'll pay you as much as you ask.",
"Thank you, I don't need anything.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, you will pay me,",
"for secret hand-to-hand combat techniques?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, you will pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for secret defense techniques?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for the lessons of leading people?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for advice on steering the ship?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for advice on firing cannons?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for advice on reloading guns?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for advice on abortion?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, what are you going to pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for advice on repairing the ship?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Well, will you pay me,",
"for help in trade?",
"I don't seem to have enough money.",
"Yes, I'll try, tell me.",
"No, it's too much.",
"Thank you for your help, you are too kind.",
"No need, glad I could help.",
"Well, do you want to buy more elixirs?",
"Yes, perhaps more.",
"No, sorry.",
"Well, do you want to bargain?",
"Yes, I want to buy something from you.",
"No, sorry.",
"What do you want? I think we've already discussed everything.",
"Never mind.",
"What orders, captain?",
"None",
"Do you want some advice?",
"Yes, I'm interested in what you have to say.",
"No, sorry.",
"Listen, lead a righteous life and many people will be happy with you.",
"Thanks for the advice.",
"I don't advise you to go here if you are in trouble with the law. There are a lot of soldiers here. You'd better sail away from the island.",
"Interesting.",
"I'm not interested in this kind of advice. Goodbye.",
"I know a certian way to restore health if something is wrong with you. You can buy a bottle from a vendor in the city.",
"Yes, and besides that?",
"I don't have time to talk.",
"You know, if I need the latest news or any information, I always go to the innkeeper. He can answer almost all your questions.",
"Great advice, I'll use it.",
"I see that you are a military man. And you often have to participate in fights. Remember, take more officers with you. Sometimes it is impossible to survive without backup.",
"Yes, sure.",
"I can see from your stance that you are the captain, nothing less. If you need a ship, buy it at our shipyard. If suddenly there is not exactly the ship that you wanted to buy, come back in a few days, maybe by this time it will be up for sale.",
"Good advice, thanks.",
"Sometimes people who have seen a lot in this world appear in these places. You can ask them for help, and they will be able to increase your level of knowledge in one or more areas. I know for sure, their knowledge is almost priceless.",
"Good advice, thanks.",
};