#define SIMPLE_RUMOUR_NUM	95
#define CITIZEN_RUMOUR_NUM	10

string DEFAULT_TEXT[19] = {
"On dit que la flotte d'or part de Portobelo deux fois par an. Plusieurs dizaines de navires marchands protégés par des navires de guerre.  Toujours le même itinéraire : de Portobelo à La Havane, une fois arrivé à Cuba, Elle fait voile vers le nord, vers le Vieux Monde. Les cales de la flotte sont évidemment remplies de trésors inestimables.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"On dit que la flotte d'or part de Portobelo deux fois par an. Plusieurs dizaines de navires marchands protégés par des navires de guerre.  Toujours le même itinéraire : de Portobelo à La Havane, une fois arrivé à Cuba, Elle fait voile vers le nord, vers le Vieux Monde. Les cales de la flotte sont évidemment remplies de trésors inestimables.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"On dit que la flotte d'or part de Portobelo deux fois par an. Plusieurs dizaines de navires marchands protégés par des navires de guerre.  Toujours le même itinéraire : de Portobelo à La Havane, une fois arrivé à Cuba, Elle fait voile vers le nord, vers le Vieux Monde. Les cales de la flotte sont évidemment remplies de trésors inestimables.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"On dit que la flotte d'or part de Portobelo deux fois par an. Plusieurs dizaines de navires marchands protégés par des navires de guerre.  Toujours le même itinéraire : de Portobelo à La Havane, une fois arrivé à Cuba, Elle fait voile vers le nord, vers le Vieux Monde. Les cales de la flotte sont évidemment remplies de trésors inestimables.",
};
/// Если новостей нет .
string NO_RUMOUR_TEXT[SIMPLE_RUMOUR_NUM] = {
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.", //30
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.", //60
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.",
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
"On dit que l'Europe va exploser à nouveau. Une nouvelle guerre s'annonce et, comme toujours, ce sont les gens du peuple qui en feront les frais. J'espère qu'elle n'arrivera pas jusqu'ici, nous avons déjà assez de problèmes.", //90
"Rien de spécial à raconter. La vie se déroule paisiblement et tranquillement. Étonnamment calme, je vous le dis.",
"C'est calme par ici. Les navires ne jettent pas souvent l'ancre dans les eaux avoisinantes, donc rien d'intéressant à vous dire.",
"L'arrivée de votre navire, c'est de cela que nous parlons !",
"Je ne me souviens de rien d'intéressant. Même les bagarres dans les tavernes sont rares ici.",
"Je doute de pouvoir vous dire quoi que ce soit de spécial, cela fait un moment que je n'ai pas entendu de nouvelles.",
};

// Слухи капитанов
string CAPTAIN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Méfiez-vous des navires sur le point de couler. Certains capitaines peuvent mettre le feu à leurs propres réserves de poudre, juste pour vous donner, à vous et à vos alliés, un tout dernier coup de l'enfer. Ce n'est pas la façon la plus courante de dire au revoir, mais soyez tout de même prudent.",
"Ne sous-estimez pas les boulets ronds, capitaine ! Ils peuvent sembler ordinaires et ennuyeux, mais ils ont la plus grande portée et peuvent infliger des dégâts convenables à presque tout. Et ils sont bon marché. Ce qui est toujours une bonne chose. Tout le monde ne peut pas se permettre d'acheter des bombes et des boulets chaînés tout le temps.",
"Méfiez-vous des navires sur le point de couler. Certains capitaines peuvent mettre le feu à leurs propres réserves de poudre, juste pour vous donner, à vous et à vos alliés, un tout dernier coup de l'enfer. Ce n'est pas la façon la plus courante de dire au revoir, mais soyez tout de même prudent.",
"Ne sous-estimez pas les boulets ronds, capitaine ! Ils peuvent sembler ordinaires et ennuyeux, mais ils ont la plus grande portée et peuvent infliger des dégâts convenables à presque tout. Et ils sont bon marché. Ce qui est toujours une bonne chose. Tout le monde ne peut pas se permettre d'acheter des bombes et des boulets chaînés tout le temps.",
"Méfiez-vous des navires sur le point de couler. Certains capitaines peuvent mettre le feu à leurs propres réserves de poudre, juste pour vous donner, à vous et à vos alliés, un tout dernier coup de l'enfer. Ce n'est pas la façon la plus courante de dire au revoir, mais soyez tout de même prudent.",
"Ne sous-estimez pas les boulets ronds, capitaine ! Ils peuvent sembler ordinaires et ennuyeux, mais ils ont la plus grande portée et peuvent infliger des dégâts convenables à presque tout. Et ils sont bon marché. Ce qui est toujours une bonne chose. Tout le monde ne peut pas se permettre d'acheter des bombes et des boulets chaînés tout le temps.",
"Méfiez-vous des navires sur le point de couler. Certains capitaines peuvent mettre le feu à leurs propres réserves de poudre, juste pour vous donner, à vous et à vos alliés, un tout dernier coup de l'enfer. Ce n'est pas la façon la plus courante de dire au revoir, mais soyez tout de même prudent.",
"Ne sous-estimez pas les boulets ronds, capitaine ! Ils peuvent sembler ordinaires et ennuyeux, mais ils ont la plus grande portée et peuvent infliger des dégâts convenables à presque tout. Et ils sont bon marché. Ce qui est toujours une bonne chose. Tout le monde ne peut pas se permettre d'acheter des bombes et des boulets chaînés tout le temps.",
"Méfiez-vous des navires sur le point de couler. Certains capitaines peuvent mettre le feu à leurs propres réserves de poudre, juste pour vous donner, à vous et à vos alliés, un tout dernier coup de l'enfer. Ce n'est pas la façon la plus courante de dire au revoir, mais soyez tout de même prudent.",
"Ne sous-estimez pas les boulets ronds, capitaine ! Ils peuvent sembler ordinaires et ennuyeux, mais ils ont la plus grande portée et peuvent infliger des dégâts convenables à presque tout. Et ils sont bon marché. Ce qui est toujours une bonne chose. Tout le monde ne peut pas se permettre d'acheter des bombes et des boulets chaînés tout le temps.",
};

// Слухи мещан мужские
string CITIZEN_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Le commerce peut être un moyen de faire fortune, mais je vous suggère d'engager un trésorier, car les affaires sont délicates ici, dans les colonies. Sans un bon trésorier, ils vous mangeront, vous et vos sous. Alors peut-être devriez-vous envisager de travailler pour un gouverneur ou quelque chose comme ça. Ce n'est pas si risqué et c'est très honorable.",
"Allez dans une taverne si vous cherchez quelque chose de particulier. Je n'ai rien à vous dire.",
"Le commerce peut être un moyen de faire fortune, mais je vous suggère d'engager un trésorier, car les affaires sont délicates ici, dans les colonies. Sans un bon trésorier, ils vous mangeront, vous et vos sous. Alors peut-être devriez-vous envisager de travailler pour un gouverneur ou quelque chose comme ça. Ce n'est pas si risqué et c'est très honorable.",
"Allez dans une taverne si vous cherchez quelque chose de particulier. Je n'ai rien à vous dire.",
"Le commerce peut être un moyen de faire fortune, mais je vous suggère d'engager un trésorier, car les affaires sont délicates ici, dans les colonies. Sans un bon trésorier, ils vous mangeront, vous et vos sous. Alors peut-être devriez-vous envisager de travailler pour un gouverneur ou quelque chose comme ça. Ce n'est pas si risqué et c'est très honorable.",
"Allez dans une taverne si vous cherchez quelque chose de particulier. Je n'ai rien à vous dire.",
"Le commerce peut être un moyen de faire fortune, mais je vous suggère d'engager un trésorier, car les affaires sont délicates ici, dans les colonies. Sans un bon trésorier, ils vous mangeront, vous et vos sous. Alors peut-être devriez-vous envisager de travailler pour un gouverneur ou quelque chose comme ça. Ce n'est pas si risqué et c'est très honorable.",
"Allez dans une taverne si vous cherchez quelque chose de particulier. Je n'ai rien à vous dire.",
"Le commerce peut être un moyen de faire fortune, mais je vous suggère d'engager un trésorier, car les affaires sont délicates ici, dans les colonies. Sans un bon trésorier, ils vous mangeront, vous et vos sous. Alors peut-être devriez-vous envisager de travailler pour un gouverneur ou quelque chose comme ça. Ce n'est pas si risqué et c'est très honorable.",
"Allez dans une taverne si vous cherchez quelque chose de particulier. Je n'ai rien à vous dire.",
};

// Слухи мещан женские
string CITIZEN_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Si vous ne pouvez pas engager suffisamment de personnes dans les tavernes, cherchez dans les rues. Il arrive que des marins se promènent dans la ville, à la recherche du bon capitaine.",
"Cet endroit est barbare ! La plupart du temps. Les hommes du coin sont des brutes sans honneur. S'il vous plaît, n'ignorez pas les femmes qui ont besoin d'aide. Nous avons si peu de protecteurs ici. Faites preuve d'un peu de dignité !",
"Si vous ne pouvez pas engager suffisamment de personnes dans les tavernes, cherchez dans les rues. Il arrive que des marins se promènent dans la ville, à la recherche du bon capitaine.",
"Cet endroit est barbare ! La plupart du temps. Les hommes du coin sont des brutes sans honneur. S'il vous plaît, n'ignorez pas les femmes qui ont besoin d'aide. Nous avons si peu de protecteurs ici. Faites preuve d'un peu de dignité !",
"Si vous ne pouvez pas engager suffisamment de personnes dans les tavernes, cherchez dans les rues. Il arrive que des marins se promènent dans la ville, à la recherche du bon capitaine.",
"Cet endroit est barbare ! La plupart du temps. Les hommes du coin sont des brutes sans honneur. S'il vous plaît, n'ignorez pas les femmes qui ont besoin d'aide. Nous avons si peu de protecteurs ici. Faites preuve d'un peu de dignité !",
"Si vous ne pouvez pas engager suffisamment de personnes dans les tavernes, cherchez dans les rues. Il arrive que des marins se promènent dans la ville, à la recherche du bon capitaine.",
"Cet endroit est barbare ! La plupart du temps. Les hommes du coin sont des brutes sans honneur. S'il vous plaît, n'ignorez pas les femmes qui ont besoin d'aide. Nous avons si peu de protecteurs ici. Faites preuve d'un peu de dignité !",
"Si vous ne pouvez pas engager suffisamment de personnes dans les tavernes, cherchez dans les rues. Il arrive que des marins se promènent dans la ville, à la recherche du bon capitaine.",
"Cet endroit est barbare ! La plupart du temps. Les hommes du coin sont des brutes sans honneur. S'il vous plaît, n'ignorez pas les femmes qui ont besoin d'aide. Nous avons si peu de protecteurs ici. Faites preuve d'un peu de dignité !",
};

// Слухи дворян
string NOBLE_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Maîtrisez votre rapière, monsieur. Elle vous sauvera la vie et protégera votre honneur. Mais, pour être tout à fait honnête, les voyous du coin ne méritent pas une rapière, mais une hache.",
"Gardez toujours suffisamment de poudre et de balles à votre disposition. Vous ne voulez pas être à court de munitions au milieu d'un combat. Garder un pistolet supplémentaire ne serait pas de trop. Ces choses explosent souvent...",
"Maîtrisez votre rapière, monsieur. Elle vous sauvera la vie et protégera votre honneur. Mais, pour être tout à fait honnête, les voyous du coin ne méritent pas une rapière, mais une hache.",
"Gardez toujours suffisamment de poudre et de balles à votre disposition. Vous ne voulez pas être à court de munitions au milieu d'un combat. Garder un pistolet supplémentaire ne serait pas de trop. Ces choses explosent souvent...",
"Maîtrisez votre rapière, monsieur. Elle vous sauvera la vie et protégera votre honneur. Mais, pour être tout à fait honnête, les voyous du coin ne méritent pas une rapière, mais une hache.",
"Gardez toujours suffisamment de poudre et de balles à votre disposition. Vous ne voulez pas être à court de munitions au milieu d'un combat. Garder un pistolet supplémentaire ne serait pas de trop. Ces choses explosent souvent...",
"Maîtrisez votre rapière, monsieur. Elle vous sauvera la vie et protégera votre honneur. Mais, pour être tout à fait honnête, les voyous du coin ne méritent pas une rapière, mais une hache.",
"Gardez toujours suffisamment de poudre et de balles à votre disposition. Vous ne voulez pas être à court de munitions au milieu d'un combat. Garder un pistolet supplémentaire ne serait pas de trop. Ces choses explosent souvent...",
"Maîtrisez votre rapière, monsieur. Elle vous sauvera la vie et protégera votre honneur. Mais, pour être tout à fait honnête, les voyous du coin ne méritent pas une rapière, mais une hache.",
"Gardez toujours suffisamment de poudre et de balles à votre disposition. Vous ne voulez pas être à court de munitions au milieu d'un combat. Garder un pistolet supplémentaire ne serait pas de trop. Ces choses explosent souvent...",
};

// Слухи дворянок
string NOBLE_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Vous avez l'air d'un homme d'honneur. Un noble. Si vous étiez d'un autre acabit, je vous enverrais dans une taverne pour questionner les gens qui s'y trouvent.",
"Saviez-vous, capitaine, qu'il y a toutes sortes d'objets magiques dans cette région ? L'Église ne l'approuve peut-être pas, mais tout le monde utilise des talismans et des amulettes.",
"Vous avez l'air d'un homme d'honneur. Un noble. Si vous étiez d'un autre acabit, je vous enverrais dans une taverne pour questionner les gens qui s'y trouvent.",
"Saviez-vous, capitaine, qu'il y a toutes sortes d'objets magiques dans cette région ? L'Église ne l'approuve peut-être pas, mais tout le monde utilise des talismans et des amulettes.",
"Vous avez l'air d'un homme d'honneur. Un noble. Si vous étiez d'un autre acabit, je vous enverrais dans une taverne pour questionner les gens qui s'y trouvent.",
"Saviez-vous, capitaine, qu'il y a toutes sortes d'objets magiques dans cette région ? L'Église ne l'approuve peut-être pas, mais tout le monde utilise des talismans et des amulettes.",
"Vous avez l'air d'un homme d'honneur. Un noble. Si vous étiez d'un autre acabit, je vous enverrais dans une taverne pour questionner les gens qui s'y trouvent.",
"Saviez-vous, capitaine, qu'il y a toutes sortes d'objets magiques dans cette région ? L'Église ne l'approuve peut-être pas, mais tout le monde utilise des talismans et des amulettes.",
"Vous avez l'air d'un homme d'honneur. Un noble. Si vous étiez d'un autre acabit, je vous enverrais dans une taverne pour questionner les gens qui s'y trouvent.",
"Saviez-vous, capitaine, qu'il y a toutes sortes d'objets magiques dans cette région ? L'Église ne l'approuve peut-être pas, mais tout le monde utilise des talismans et des amulettes.",
};

// Слухи матросов
string SAILOR_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Difficile de trouver un bon capitaine de nos jours. La plupart d'entre eux veulent que nous soyons leurs soldats ou leurs esclaves. Ou les deux. Qu'ils aillent se faire voir. J'espère que vous êtes différent.",
"Rien d'intéressant. Les choses seront intéressantes lorsque nos provisions seront épuisées.",
"Difficile de trouver un bon capitaine de nos jours. La plupart d'entre eux veulent que nous soyons leurs soldats ou leurs esclaves. Ou les deux. Qu'ils aillent se faire voir. J'espère que vous êtes différent.",
"Rien d'intéressant. Les choses seront intéressantes lorsque nos provisions seront épuisées.",
"Difficile de trouver un bon capitaine de nos jours. La plupart d'entre eux veulent que nous soyons leurs soldats ou leurs esclaves. Ou les deux. Qu'ils aillent se faire voir. J'espère que vous êtes différent.",
"Rien d'intéressant. Les choses seront intéressantes lorsque nos provisions seront épuisées.",
"Difficile de trouver un bon capitaine de nos jours. La plupart d'entre eux veulent que nous soyons leurs soldats ou leurs esclaves. Ou les deux. Qu'ils aillent se faire voir. J'espère que vous êtes différent.",
"Rien d'intéressant. Les choses seront intéressantes lorsque nos provisions seront épuisées.",
"Difficile de trouver un bon capitaine de nos jours. La plupart d'entre eux veulent que nous soyons leurs soldats ou leurs esclaves. Ou les deux. Qu'ils aillent se faire voir. J'espère que vous êtes différent.",
"Rien d'intéressant. Les choses seront intéressantes lorsque nos provisions seront épuisées.",
};

// Если новостей нет в LSC
string NO_RUMOUR_LSC_TEXT[5] = {
"C'est plutôt ennuyeux ici. Quelles sont les nouvelles qui vous intéressent ?",
"Des ragots ? Rien à dire, tout va bien jusqu'à ce que les Rivados et les Narwals recommencent à se battre.",
"Rien d'intéressant... Ce sera intéressant lorsque nos provisions alimentaires s'épuiseront.",
"Comme toujours. Ennuyeux. Peut-être que les pirates vont botter le cul des clans. Cela mettrait de la bonne humeur.",
"Pas de nouvelles, pas de ragots. Jusqu'à ce que les clans commencent à s'entretuer, bien sûr.",
};
